name: Deploy Prisma Migrations

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2  # <== This is the key fix

      - name: Install dependencies
        run: npm install

      - name: Deploy Prisma Migrations
        run: |
          if git diff --name-only HEAD~1 HEAD | grep -q packages/db/prisma/migrations; then
            echo "New migrations found. Deploying..."
            npx prisma migrate deploy --schema=packages/db/prisma/schema.prisma
          else
            echo "No new migrations. Skipping deploy."
          fi
        env:
          DATABASE_URL: ${{ secrets.PRODUCTION_DATABASE_URL }}
